version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_v2
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres.wmhghfyzkbhscmcubnzh:Valid8Rizal2026@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_v2
    ports:
      - "5173:5173"
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
    external: true
    name: valid8_docker_final_postgres_data
